name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test

      - name: Post Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        - name: Test only
        if: github.event_name != 'push'
        run: npm test
      - name: Test + Publish Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        if: github.event_name == 'push'
        with:
          threshold: 80
